### PR TITLE
Fix: kampvoorkeur grafiek

### LINKED ISSUE #105: Weggevallen labels bij grafiek kampvoorkeur deelnemers
In AAS --> Grafieken --> Kampvoorkeur deelnemers.

Opgemerkt door Fieke met de volgende screenshot:

image

Labels zijn wel zichtbaar via mouse-over maar de weergave op de y-as is kennelijk stuk.

### PR DESCRIPTION
**Pull request by robinklaassen**
Fixes #105 

* Zat ermee te prutsen
* Kwam er niet uit
* Besloot om te schrijven naar standaard Google Charts zoals de rest van de grafieken (behalve inschrijvingen)
* Werkt prima
* Zitten filosoferen waarom ik überhaupt ooit Lavacharts erbij gehaald heb
* Kwam er niet uit
* Lavacharts weggetiefd

Profit :)

### CODE REVIEW

**Comment by robinklaassen** [comment]
Eerst #103 doen, die staat al langer open. Downmerge ik daarna wel hierin.

File: app/Http/Controllers/PagesController.php [hunk 1]
```diff
@@ -492,49 +492,21 @@ public function graphs()
...
-					$camp_prefs[$opt]++;
-				} else {
-					$camp_prefs[$opt] = 1;
-				}
-			}
+		$reviews = \App\Review::whereNotNull('kampkeuze')->pluck('kampkeuze')->toArray(); // note: 2D array
+
+		$reviews_flat = [];
+		foreach ($reviews as $r) {
+			$reviews_flat = array_merge($reviews_flat, $r);
```
Comment (blackshadev) [inline app/Http/Controllers/PagesController.php:499]:
```suggestion
		$reviews = \App\Review::whereNotNull('kampkeuze')->pluck('kampkeuze');
		$prefs_review_count = $reviews->count();
		$reviews_flat = $reviews->flatten()->toArray();
```
This can be simplified to this above.  The `$prefs_review_count` is also done with laravel collections this way.
I'd like to fallback to laravel collections as much as possible, as it is easier to read, and more consistent with laravel itself.

File: database/seeds/ReviewTableSeeder.php [hunk 2]
```diff
@@ -45,5 +45,37 @@ public function run()
             'tip' => 'Meer chocola',
             'verder' => 'Ik besta niet echt'
         ]);
+
+        Review::create([
```
Comment (blackshadev) [inline database/seeds/ReviewTableSeeder.php:49]: Can you add one more? I think that you can test more with at least two records.

File: resources/views/pages/graphs.blade.php [hunk 3]
```diff
@@ -228,6 +228,24 @@ function drawChart() {
...
+			  minValue: 0,
+			  gridlines: {
+				  count: -1
+			  }
+		  },
+          legend: { position: 'none' }
+        };
+
+	var chart = new google.visualization.BarChart(document.getElementById('camp_preference_chart'));
+	chart.draw(data, options);
```
Comment (blackshadev) [inline resources/views/pages/graphs.blade.php:247]: With pr #103 you can simplify this to a function call to `drawGoogleChart`

File: app/Http/Controllers/PagesController.php (hunk 1 above)
Comment (robinklaassen) [reply app/Http/Controllers/PagesController.php:499]: I've actually been searching for a php way to flatten an array but couldn't find any. Didn't think to check the Laravel specific methods... nice one.

File: resources/views/pages/graphs.blade.php (hunk 3 above)
Comment (robinklaassen) [reply resources/views/pages/graphs.blade.php:247]: Yeah saw that. Will be sure to implement that.

Comment (robinklaassen) [reply resources/views/pages/graphs.blade.php:261]: @blackshadev drawback to current implementation of `drawGoogleChart` is that you have to specify the column names and types in the view, instead of in the controller (where I think it fits better because it's part of the data logic). What's your opinion of this?

Comment (blackshadev) [reply resources/views/pages/graphs.blade.php:259]: Yeah I'd think it is better suited at the controller part. To me the reason for it being in JS is: 
 1. The library requires it to be there
 2. It is part of the displaying / view. 

But you require the data (columns) to be there, which is the responsibility of the controller. So it's better to do it there.
Maybe we can write a wrapper around it such that the wrapper injects the JS parts into the view, with the correct columns etc.

Comment (robinklaassen) [reply resources/views/pages/graphs.blade.php]: Concluded that I can't be bothered to rewrite at the moment. Refactored it to call `drawGoogleChart`, we can further overhaul the graph system with the next update to it.
